database:
  default:
    dsn: mysql:host=bit-server.thruhere.net; dbname=vkara
    user: lude
    password: $password

logger:
  errorFileAppender:
    class: Mars_LoggerFileAppender
    file: error.log
    rotate:
      type: date
      datePattern: Y-m

cpanel:
  password: 2ea6de

minify:
  js:
    bootstrap:
      - "bootstrap/bootstrap-alerts.js"
      - "bootstrap/bootstrap-buttons.js"
      - "bootstrap/bootstrap-dropdown.js"
      - "bootstrap/bootstrap-modal.js"
      - "bootstrap/bootstrap-popover.js"
      - "bootstrap/bootstrap-scrollspy.js"
      - "bootstrap/bootstrap-tabs.js"
      - "bootstrap/bootstrap-twipsy.js"
